teams:
- name: aifaq-maintainers
  maintainers:
  - gcapuzzi
  members:
  - swaptr
- name: cc-tools-admin
  maintainers:
  - samuelvenzi
  members:
  - goledger
- name: cc-tools-committers
  maintainers:
  - samuelvenzi
  members:
  - andremacedopv
  - AlineLermen
- name: cc-tools-maintainers
  maintainers:
  - samuelvenzi
  members:
  - andremacedopv
  - lucas-campelo
  - mikaellafs
- name: documentation-template-committers
  maintainers:
  - tkuhrt
- name: electrodo-docs-maintainers
  maintainers:
  - tkuhrt
- name: fablo-admins
  maintainers:
  - dzikowski
  members:
  - Hejwo
- name: fablo-maintainers
  maintainers:
  - dzikowski
  members:
  - Hejwo
  - umegbewe
- name: fabric-builder-k8s-maintainers
  maintainers:
  - jt-nti
- name: fabric-debugger-admins
  maintainers:
  - arsulegai
- name: fabric-debugger-committers
  maintainers:
  - arsulegai
  members:
  - technomad01
  - urgetolearn
  - varshapichandi30
- name: fabric-operations-console-maintainers
  maintainers:
  - dshuffma-ibm
  members:
  - denyeart
  - ketulsha
  - MuthuSundaravadivel
  - shoaebjindani
  - Thomas-Leung
- name: fabric-chaincode-builder-maintainers
  maintainers:
  - Thomas-Leung
  members:
  - shoaebjindani
  - MuthuSundaravadivel
- name: fabric-ansible-collection-committers
  maintainers:
  - mbwhite
  members:
  - MuthuSundaravadivel
  - celder628
  - modemn
- name: fabric-operator-committers
  maintainers:
  - denyeart
  members:
  - asararatnakar
  - shoaebjindani
- name: fabric-smart-client-committers
  maintainers:
  - adecaro
  - yacovm
  members:
  - aaadir
  - AkramBitar
  - ale-linux
  - alexandrosfilios
  - arner
  - barvhaim
  - drucker-nir
  - Effi-S
  - HayimShaul
  - KElkhiyaoui
  - kushnireyal
  - mbrandenburger
  - omri-so
  - SaidAltury-ibm
- name: fabric-token-java-sdk-maintainers
  maintainers:
  - adecaro
- name: fabric-token-sdk-committers
  maintainers:
  - adecaro
  - yacovm
  members:
  - aaadir
  - AkramBitar
  - ale-linux
  - alexandrosfilios
  - arner
  - barvhaim
  - drucker-nir
  - Effi-S
  - HayimShaul
  - KElkhiyaoui
  - kushnireyal
  - mbrandenburger
  - omri-so
  - SaidAltury-ibm
  - sreenidhidrIBM
- name: hlf-connector-maintainers
  maintainers:
  - arsulegai
  members:
  - adityajoshi12
  - nidhi-singh02
  - nithin-pankaj
- name: hyperledger-community-management-tools-committers
  maintainers:
  - tkuhrt
- name: lab-stewards
  maintainers:
  - tkuhrt
  members:
  - alvaropicazo
  - mbrandenburger
  - nidhi-singh02
- name: learning-tokens-maintainers
  maintainers:
  - TanjinAlam
  members:
  - noemi128
  - AlfonsoGovela 
  - NeoZ666
- name: learning-tokens-mentees
  maintainers:
  - noemi128
  members:
  - Ankita0112
  - AviraL0013
  - HariomDhage
  - Vaibhav701161
  - harsh-a-parihar
- name: microfab-maintainers
  maintainers:
  - denyeart
  members:
  - celder628
- name: organizational-agent-committers
  maintainers:
  - swcurran
- name: perun-committers
  maintainers:
  - iljabvh
  - DragonDev1906
  - tinnendo
  members:
  - RmbRT
  - NhoxxKienn
  - cryptphil
  - ravi0131
  - sophia1ch
- name: perun
  maintainers:
  - iljabvh
  - DragonDev1906
  - tinnendo
  members:
  - RmbRT
  - NhoxxKienn
  - cryptphil
  - ravi0131
  - sophia1ch
- name: fabric-ansible-collection
  teams:
    fabric-ansible-collection-committers: maintain
    security-managers: read
  visibility: public
- name: security-managers
  maintainers:
  - hartm
  - ryjones
- name: security-notices
  maintainers:
  - ryjones
  - tkuhrt
- name: smartbft-maintainers
  maintainers:
  - yacovm
  members:
  - C0rWin
  - pfi79
  - tock-ibm
  - HagarMeir
- name: splice-admins
  maintainers:
  - waynecollier-da
  members:
  - isegall-da
  - martinflorian-da
  - moritzkiefer-da
  - ray-roestenburg-da
  - canton-network-da
- name: splice-contributors
  maintainers:
  - waynecollier-da
  members:
  - meiersi-da
  - rautenrieth-da
  - stephencompall-DA
  - nicu-da
  - fayi-da
  - OriolMunoz-da
  - julientinguely-da
  - pawelperek-da
  - pasindutennage-da
  - mblaze-da
  - dfordivam
  - jose-velasco-ieu
  - jagathweerasinghe-da
  - krzysztofczyz-da
- name: splice-wallet-kernel-admins
  maintainers:
  - isegall-da
  members:
  - mjuchli-da
  - PHOL-DA
  - daravep
- name: splice-wallet-kernel-contributors
  maintainers:
  - PHOL-DA
  members:
  - alexmatson-da
  - davidrichards-da
  - matteolimberto-da
  - pawelstepien-da
  - da-tanabe
  - rukmini-basu-da
  - fayi-da
  - mateuszpiatkowski-da
  - Stephan-Canton
  - joel-da
  - v9n
  - sbile
  - pixelplex
  - dasormeter
  - jordan-da
  - sammy-da
  - jonathan-klein-da
  - jaspervdj-da
- name: yui-committers
  maintainers:
  - '3100'
  - bluele
  members:
  - siburu
- name: yui-triage
  maintainers:
  - bluele
  members:
  - abicky
  - dai1975
repositories:
- name: acapy-java-client
  teams:
    organizational-agent-committers: maintain
    security-managers: read
  visibility: public
- name: aifaq
  teams:
    aifaq-maintainers: maintain
    security-managers: read
  visibility: public
- name: cardea
  teams:
    security-managers: read
  visibility: public
- name: cardea-docker
  teams:
    security-managers: read
  visibility: public
- name: cardea-health-issuer-controller
  teams:
    security-managers: read
  visibility: public
- name: cardea-health-issuer-ui
  teams:
    security-managers: read
  visibility: public
- name: cardea-mobile-agent
  teams:
    security-managers: read
  visibility: public
- name: cardea-mobile-secondary-verifier-agent
  teams:
    security-managers: read
  visibility: public
- name: cardea-primary-verifier-controller
  teams:
    security-managers: read
  visibility: public
- name: cardea-primary-verifier-ui
  teams:
    security-managers: read
  visibility: public
- name: cardea-secondary-verifier-controller
  teams:
    security-managers: read
  visibility: public
- name: cardea-secondary-verifier-ui
  teams:
    security-managers: read
  visibility: public
- name: cardea.app
  teams:
    security-managers: read
  visibility: public
- name: cc-tools
  teams:
    cc-tools-admin: maintain
    cc-tools-committers: write
    cc-tools-maintainers: maintain
    security-managers: read
  visibility: public
- name: cc-tools-demo
  teams:
    cc-tools-admin: maintain
    cc-tools-committers: write
    cc-tools-maintainers: maintain
    security-managers: read
  visibility: public
- name: cc-tools-doc
  teams:
    cc-tools-admin: maintain
    cc-tools-committers: write
    cc-tools-maintainers: maintain
    security-managers: read
  visibility: public
- name: documentation-template
  teams:
    documentation-template-committers: maintain
    security-managers: read
  visibility: public
- name: Electrodo.Docs
  teams:
    security-managers: read
  visibility: public
- name: fablo
  teams:
    fablo-admins: admin
    fablo-maintainers: maintain
    security-managers: read
  visibility: public
- name: fabric-ansible-collection
  teams:
    fabric-ansible-collection-committers: maintain
    security-managers: read
  visibility: public
- name: fabric-builder-k8s
  teams:
    fabric-builder-k8s-maintainers: admin
    security-managers: read
  visibility: public
- name: fabric-chaincode-builder
  teams:
    fabric-chaincode-builder-maintainers: maintain
    security-managers: read
  visibility: public
- name: fabric-channeled-add-ons-gen
  teams:
    security-managers: read
  visibility: public
- name: fabric-debugger
  teams:
    fabric-debugger-admins: maintain
    fabric-debugger-committers: write
    security-managers: read
  visibility: public
- name: fabric-operations-console
  teams:
    fabric-operations-console-maintainers: maintain
    security-managers: read
  visibility: public
- name: fabric-operator
  teams:
    fabric-operator-committers: admin
    security-managers: read
  visibility: public
- name: fabric-smart-client
  teams:
    fabric-smart-client-committers: admin
    security-managers: read
  visibility: public
- name: fabric-token-sdk
  teams:
    fabric-token-sdk-committers: admin
    security-managers: read
  visibility: public
- name: go-perun
  teams:
    perun-committers: write
    security-managers: read
  visibility: public
- name: governance
  teams:
    lab-stewards: maintain
    security-managers: read
  visibility: public
- name: hlf-connector
  teams:
    hlf-connector-maintainers: maintain
    security-managers: read
  visibility: public
- name: hyperledger-community-management-tools
  teams:
    hyperledger-community-management-tools-committers: maintain
    security-managers: read
  visibility: public
- name: learning-tokens
  teams:
    learning-tokens-maintainers: maintain
    learning-tokens-mentees: write
    security-managers: read
  visibility: public
- name: microfab
  teams:
    microfab-maintainers: maintain
    security-managers: read
  visibility: public
- name: perun-cosmwasm-backend
  teams:
    perun-committers: maintain
    security-managers: read
  visibility: public
- name: perun-cosmwasm-contract
  teams:
    perun-committers: maintain
    security-managers: read
  visibility: public
- name: perun-credential-payment
  teams:
    perun-committers: write
    security-managers: read
  visibility: public
- name: perun-doc
  teams:
    perun-committers: write
    security-managers: read
  visibility: public
- name: perun-eth-backend
  teams:
    perun-committers: write
    security-managers: read
  visibility: public
- name: perun-eth-contracts
  teams:
    perun-committers: write
    security-managers: read
  visibility: public
- name: perun-node
  teams:
    perun-committers: write
    security-managers: read
  visibility: public
- name: perun-proposals
  teams:
    perun-committers: write
    security-managers: read
  visibility: public
- name: perun-rs
  teams:
    perun-committers: write
    security-managers: read
  visibility: public
- name: pluggable-hcs
  teams:
    security-managers: read
  visibility: public
- name: SmartBFT
  teams:
    security-managers: read
    smartbft-maintainers: maintain
  visibility: public
- name: splice
  teams:
    security-managers: read
    splice-admins: admin
    splice-contributors: maintain
  visibility: public
- name: splice-runner-container-hooks
  teams:
    security-managers: read
    splice-admins: admin
    splice-contributors: maintain
  visibility: public
- name: splice-shared-gha
  teams:
    security-managers: read
    splice-admins: admin
    splice-contributors: maintain
  visibility: public
- name: splice-wallet-kernel
  teams:
    security-managers: read
    splice-wallet-kernel-admins: admin
    splice-wallet-kernel-contributors: maintain
  visibility: public
- name: TDIDN
  teams:
    security-managers: read
  visibility: public
- name: yui-corda-ibc
  teams:
    security-managers: read
    yui-committers: maintain
  visibility: public
- name: yui-docs
  teams:
    security-managers: read
    yui-committers: maintain
  visibility: public
- name: yui-fabric-ibc
  teams:
    security-managers: read
    yui-committers: maintain
  visibility: public
- name: yui-ibc-solidity
  teams:
    security-managers: read
    yui-committers: maintain
    yui-triage: triage
  visibility: public
- name: yui-relayer
  teams:
    security-managers: read
    yui-committers: maintain
    yui-triage: triage
  visibility: public
